export const dataMaps: any[] = [
  {
    id: '1',
    name: 'Мапа України з дерева та Лед підсвіткою (Епсілон)',
    price: 7000,
    tags: ['мапа  дерево', 'настінний декор'],
    favorite: false,
    stars: 5,
    imageUrl: '/assets/map-ukraine-led-3d-epsilon.jpg',
    producer: 'Mixdekor',
  },
  {
    id: '2',
    name: 'Мапа України з підсвіткою (Сіро-натуральна)',
    price: 7000,
    tags: ['мапа  україни', 'настінний декор'],
    favorite: true,
    stars: 4,
    imageUrl: '/assets/map-ukraine-led-3d-greys-natur.jpg',
    producer: 'Mixdekor',
  },
  {
    id: '3',
    name: 'Мапа України з дерева та Лед підсвіткою річок (Стоун)',
    price: 10000,
    tags: ['мапа  дерево', 'карта з річками'],
    favorite: true,
    stars: 5,
    imageUrl: '/assets/map-ukraine-led-3d-rivers-stoun.jpg',
    producer: 'Mixdekor',
  },
  {
    id: '4',
    name: '3Д мапа України з дерева (Епсілон)',
    price: 2000,
    tags: ['мапа  дерево', '3д карта'],
    favorite: false,
    stars: 4,
    imageUrl: '/assets/map-ukraine-3d-epsilon.jpg',
    producer: 'Mixdekor',
  },
  {
    id: '5',
    name: 'Мапа України з дерева та річками (Коричнева)',
    price: 5000,
    tags: ['мапа україни', 'річки україни'],
    favorite: false,
    stars: 4,
    imageUrl: '/assets/map-ukraine-3d-rivers-browns.jpg',
    producer: 'Mixdekor',
  },
];

export const users: any[] = [
  {
    name: "Oleksandr Voronko",
    email: "voronko.oleksandr@gmail.com",
    password: "7777777",
    address: "Lviv",
    isAdmin: true,
  },
  {
    name: "Oleksandr Voron",
    email: "voronko_o@ukr.net",
    password: "1111111",
    address: "Vynnyky",
    isAdmin: false,
  },
];